# Generated by Django 3.1.1 on 2020-11-20 05:45

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20201119_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar/img_avatar2.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='subtaskcomment',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_comment', to='main.subtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
