# Generated by Django 3.1.1 on 2020-11-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201120_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
    ]
